### ISSUE TITLE
erorr

### ISSUE THREAD

**Issue by yekayee** [irisan-kentang/Cheat-Ninja-Legends-Web-UI#1]
![image](https://user-images.githubusercontent.com/17975832/147297394-8390af19-93ae-414d-9be8-034c459d5558.png)

**Comment by yekayee** [comment]
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'

**Comment by irisan-kentang** [comment]
fixed
